<link href="../style.css" rel="stylesheet" type="text/css"> <table border="0" cellpadding="0" cellspacing="0" background="imagenes/backgris.gif">  <tr>     <td colspan="2"><a href="welcome.php"><img src="imagenes/logo.gif" width="189" height="96" border="0"></a></td>  </tr>  <tr>     <td colspan="2"><form name="form1" method="post" action="">        <div align="center">           <input name="textfield" type="text" size="12">          <input type="submit" name="Submit" value="Buscar">        </div>      </form></td>  </tr>  <tr>     <td colspan="2"><div align="center"><img src="imagenes/lineagrisv.gif" width="90%" height="1" vspace="5"></div></td>  </tr>  <tr bgcolor="#0070B9">     <td colspan="2" class="ligamenulefover"><strong><img src="imagenes/iconos/perfil.gif" width="13" height="14">       <a href="datos_personales.php">Perfil Acad&eacute;mico</a></strong></td>  </tr>
 </table>
 <div id="menu1">
 <table border="0" cellpadding="0" cellspacing="0" background="imagenes/backgris.gif">  <tr>     <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>    <td class="ligamenuleft">&#8226; <a href="datos_personales.php">Datos personales</a></td>  </tr>
  </table>
  </div>
  <table border="0" cellpadding="0" cellspacing="0" background="imagenes/backgris.gif">  <tr>     <td>&nbsp;</td>    <td class="ligamenuleft">&#8226; <a href="resumen.php">Resumen profesional</a></td>  </tr>  <tr>     <td>&nbsp;</td>    <td class="ligamenuleft">&#8226; <a href="datos_contractuales.php">Datos contractuales</a></td>  </tr>  <tr>     <td>&nbsp;</td>    <td class="ligamenuleft"> &#8226; <a href="formacion_academica.php">Formaci&oacute;n       y superaci&oacute;n acad&eacute;mica</a></td>  </tr>  <tr>     <td>&nbsp;</td>    <td class="ligamenuleft"> &#8226; <a href="premios.php">Premios y distinciones</a></td>  </tr>  <tr>     <td>&nbsp;</td>    <td class="ligamenuleft">&#8226; <a href="programas_estimulos.php">Programas       de apoyo</a></td>  </tr>  <tr>     <td width="18">&nbsp;</td>    <td width="178" class="ligamenuleft">&#8226; <a href="asociaciones.php">Asociaciones       acad&eacute;micas y profesionales</a></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft">&nbsp;</td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/participa.gif" width="13" height="14">       <a href="organos_colegiados.php">Participaci&oacute;n Institucional</a></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/docencia.gif" width="13" height="15">       <a href="cursos.php">Docencia</a></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/investiga.gif" width="13" height="14">       <a href="proyectos_investiga.php">Investigaci&oacute;n</a></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/difusion.gif" width="14" height="15">       <a href="conferencias.php">Divulgaci&oacute;n</a></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/apoyos.gif" width="13" height="14">       <a href="servicios.php">Apoyo a Servicios</a></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/otras.gif" width="15" height="16">       <a href="otras.php">Otras Actividades</a></strong></td>  </tr>  <tr>     <td colspan="2"><strong><img src="imagenes/botgris.gif" width="189" height="4"></strong></td>  </tr>  <tr>     <td colspan="2" bgcolor="#FFFFFF">&nbsp;</td>  </tr>  <tr>     <td colspan="2"><strong><img src="imagenes/topgris.gif" width="189" height="4"></strong></td>  </tr>  <tr>     <td colspan="2" class="ligamenuleft1"><strong><img src="imagenes/iconos/correo.gif" width="13" height="9">       <a href="http://www.enlaceestudiantil.unam.mx/correoalumnos/correoalumnos.htm" target="_blank">Consulte       su correo</a></strong></td>  </tr>  <tr>     <td colspan="2"><strong><img src="imagenes/botgris.gif" width="189" height="4"></strong></td>  </tr></table><script type="text/javascript">
 //obj = document.getElementById("menu1");
 //obj.style.display = "none";
</script>